import SideBar from "../components/SideBar";
import Head from "next/head";
import NavBar from "../components/NavBar";
import { DrawerContextProvider } from "../store/handleDrawer-context";

export default function LayoutAuth(props: any) {
  return (
    <>
      <Head>
        <title>Pel - project</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <DrawerContextProvider>
          <NavBar />
          <SideBar content={props.children} />
        </DrawerContextProvider>
      </main>
      <footer></footer>
    </>
  );
}
